import HomeMockup from '@/assets/images/homemockup';
import Button from '@/componenets/General/Button';
import PageWrapper from '@/componenets/General/PageWrapper';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const OnboardingPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Kosan App | Welcome</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        <section className="min-h-screen flex pb-9">
          <div className="flex flex-col gap-4 justify-end items-center">
            <div className="max-h-[500px] max-w-[330px] flex mb-5">
              <HomeMockup />
            </div>

            <h1 className="text-3xl text-center font-semibold">
              Welcome to <br /> Kosan App! 👋
            </h1>
            <p className="max-w-[70%] text-center">
              The best kosan looking and online booking application in this
              century.
            </p>
            <Link href={'/signin'} passHref>
              <Button as="a" className="w-full" type="button" theme="primary">
                Sign In
              </Button>
            </Link>
            <Link href={'/'} passHref>
              <Button as="a" className="w-full" type="button" theme="secondary">
                Look Around
              </Button>
            </Link>
          </div>
        </section>
      </PageWrapper>
    </>
  );
};

export default OnboardingPage;
