import PageWrapper from '@/componenets/General/PageWrapper';
import { getLocalStorageValue, setLocalStorageValue } from '@/utils/helper';
import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const Home: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    const isOnboarded = getLocalStorageValue('kosan-onboarding');

    if (isOnboarded) return;
    else {
      router.push('/onboarding');
      setLocalStorageValue('kosan-onboarding', { onboarded: true });
    }
  }, []);

  return (
    <>
      <Head>
        <title>Kosan App | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        <Link href={'/onboarding'}> onboarding</Link>
      </PageWrapper>
    </>
  );
};

export default Home;
