import AppleIcon from '@/assets/icons/AppleIcon';
import EmailIcon from '@/assets/icons/Email';
import Facebookicon from '@/assets/icons/FacebookIcon';
import GoogleIcon from '@/assets/icons/GoogleIcon';
import LockIcon from '@/assets/icons/LockIcon';
import LoginMockup from '@/assets/images/loginmockup';
import BackButton from '@/componenets/General/BackButton';
import Button from '@/componenets/General/Button';
import Input from '@/componenets/General/Form/Input';
import PageWrapper from '@/componenets/General/PageWrapper';
import { isFormValid } from '@/utils/helper';
import { LoginSchema } from '@/utils/validation';
import { useFormik } from 'formik';
import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { toast } from 'react-toastify';

interface ILoginForm {
  email: string;
  password: string;
}

const SignInPage: NextPage = () => {
  const formik = useFormik({
    onSubmit: (values: ILoginForm) => {
      console.log(values);
    },
    initialValues: {
      email: '',
      password: '',
    },
    validationSchema: LoginSchema,
  });

  return (
    <>
      <Head>
        <title>Kosan App | Sign In</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageWrapper>
        <section className="min-h-screen min-w-full flex flex-col relative">
          <BackButton redirectTo="/" />

          <section>
            <div className="flex flex-col gap-4 items-center">
              <LoginMockup className="w-[180px] h-[180px]" />

              <h1 className="text-2xl font-semibold">Login to Your Account</h1>

              <form
                className="w-full"
                onSubmit={formik.handleSubmit}
                autoComplete="off"
              >
                <Input
                  className="mb-4"
                  type={'email'}
                  name="email"
                  placeholder="Email"
                  suffixIcon={
                    <EmailIcon className="absolute top-[14px] left-4" />
                  }
                  value={formik.values.email}
                  onChange={formik.handleChange}
                  isError={isFormValid('email', formik)}
                  errMsg={formik.errors.email}
                />
                <Input
                  type={'password'}
                  name="password"
                  placeholder="Password"
                  suffixIcon={
                    <LockIcon className="absolute top-[14px] left-4 text-[#DCDEF380]" />
                  }
                  value={formik.values.password}
                  onChange={formik.handleChange}
                  isError={isFormValid('password', formik)}
                  errMsg={formik.errors.password}
                />

                <Button
                  type="submit"
                  className="w-full h-[44px] !rounded-[61px] mt-8"
                  theme="primary"
                >
                  Sign In
                </Button>
              </form>

              <div className="w-full flex flex-col">
                <div className="text-base font-medium mt-8 flex min-w-full items-center">
                  <div className="h-[1px] w-full bg-[#DCDEF380]"></div>{' '}
                  <div className="whitespace-nowrap px-2">or continue with</div>
                  <div className="h-[1px] w-full bg-[#DCDEF380]"></div>{' '}
                </div>

                <div className="flex items-center w-full justify-around mt-4">
                  <button
                    className="transition p-4 rounded-2xl bg-slate-600 hover:shadow-slate-500 hover:shadow-md"
                    onClick={() =>
                      toast.error('Sorry, coming soon!', {
                        position: 'top-right',
                        autoClose: 1000,
                        hideProgressBar: true,
                        closeOnClick: true,
                        pauseOnHover: false,
                        draggable: false,
                      })
                    }
                  >
                    <GoogleIcon />
                  </button>
                  <button
                    className="transition p-4 rounded-2xl bg-slate-600 hover:shadow-slate-500 hover:shadow-md"
                    onClick={() =>
                      toast.error('Sorry, coming soon!', {
                        position: 'top-right',
                        autoClose: 1000,
                        hideProgressBar: true,
                        closeOnClick: true,
                        pauseOnHover: false,
                        draggable: false,
                      })
                    }
                  >
                    <AppleIcon />
                  </button>
                  <button
                    className="transition p-4 rounded-2xl bg-slate-600 hover:shadow-slate-500 hover:shadow-md"
                    onClick={() =>
                      toast.error('Sorry, coming soon!', {
                        position: 'top-right',
                        autoClose: 1000,
                        hideProgressBar: true,
                        closeOnClick: true,
                        pauseOnHover: false,
                        draggable: false,
                      })
                    }
                  >
                    <Facebookicon />
                  </button>
                </div>
              </div>
            </div>
          </section>
          <h5 className="absolute inset-x-0 bottom-4 text-center">
            Don`t have an account ?{' '}
            <Link href={'/register'} passHref>
              <a className="font-medium text-blue-500">Sign Up</a>
            </Link>
          </h5>
        </section>
      </PageWrapper>
    </>
  );
};

export default SignInPage;
